version: '3.9'

services:
  
  db:
    image: postgres:15-alpine  
    container_name: postgres_db
    environment:
      
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASS}   
      POSTGRES_DB: ${DB_NAME}         
    volumes:
   
      - postgres_data:/var/lib/postgresql/data
    networks:
      
      - backend_net
    healthcheck:
      
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    container_name: fastapi_app
    
    build: .
    ports:
      
      - "8000:8000"
    environment:
      
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db  
    networks:
      
      - backend_net
    depends_on:
      db:
        
        condition: service_healthy
    restart: unless-stopped


volumes:
  
  postgres_data:
    driver: local

networks:
  
  backend_net:
    driver: bridge