name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. TESTES
  test:
    name: Rodar Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest

  # 2. BUILD E PUSH (DOCKER)
  build-and-push:
    name: Build e Push Docker
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/desafio-docker-fastapi:latest
            ${{ secrets.DOCKER_USERNAME }}/desafio-docker-fastapi:${{ github.sha }}

  # 3. PROVISIONAR INFRA (TERRAFORM)
  provision-infra:
    name: Provisionar Infraestrutura
    needs: test 
    runs-on: ubuntu-latest
    
    # Define as saídas para usar no próximo job
    outputs:
      server_ip: ${{ steps.get-ip.outputs.ipv4 }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        run: terraform apply -auto-approve

      - name: Pegar IP do Output
        id: get-ip
        working-directory: ./terraform
        run: |
          # Captura o IP cru e joga na saída do GitHub
          IP=$(terraform output -raw droplet_ip)
          echo "O IP capturado foi: $IP"
          echo "ipv4=$IP" >> $GITHUB_OUTPUT

  # 4. DEPLOY (USANDO O IP DINÂMICO)
  deploy:
    name: Deploy no Servidor
    needs: [build-and-push, provision-infra]
    runs-on: ubuntu-latest
    
    steps:
      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.provision-infra.outputs.server_ip }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Espera segurança caso seja servidor novo
            sleep 10
            
            # Lógica de clone ou update
            if [ ! -d "desafio-docker-fastapi" ]; then
              git clone https://github.com/${{ github.repository }}.git desafio-docker-fastapi
            fi
            
            cd desafio-docker-fastapi
            git pull origin main
            
            # Recria o .env básico
            echo "DB_USER=app_user" > .env
            echo "DB_PASS=app_secret_pass_123" >> .env
            echo "DB_NAME=minha_api_db" >> .env

            # Atualiza os containers
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f